// Built-in exercise library and training programs.
// Exercise types: 'wr' = weight + reps, 'r' = reps only, 't' = time, 'dt' = distance + time

export const GROUPS = [
  'Chest', 'Arms', 'Back', 'Legs', 'Shoulders', 'Core', 'Full-Body', 'Cardio', 'Other',
];

// Colour for each muscle group (used for icons, tags and card edges)
export const GROUP_COLORS = {
  Chest: '#4CAF50',
  Arms: '#F4511E',
  Back: '#3D6BFF',
  Legs: '#C0CA33',
  Shoulders: '#29B6F6',
  Core: '#8E5CFF',
  'Full-Body': '#FF9800',
  Cardio: '#EC407A',
  Other: '#9E9E9E',
};

// Set intensity levels (DECISIONS #13): shown as a coloured dot above each set
export const LEVELS = [
  { id: 'warmup', label: 'Warmup', color: '#8A8A8A' },
  { id: 'easy', label: 'Easy', color: '#43C463' },
  { id: 'normal', label: 'Normal', color: '#F2B705' },
  { id: 'hard', label: 'Hard', color: '#E53935' },
  { id: 'failure', label: 'Failure', color: '#A259FF' },
  { id: 'drop', label: 'Drop', color: '#3D8BFF' },
];

export const EQUIPMENT = [
  'Bodyweight', 'Barbell', 'Dumbbell', 'Cable', 'Machine', 'Smith Machine', 'Kettlebell', 'Band', 'Plate', 'Other',
];

// Muscle regions within each group, used as filter chips in the exercise list
export const SUBGROUPS = {
  Chest: ['Upper', 'Middle', 'Lower'],
  Back: ['Lats', 'Upper back', 'Lower back', 'Traps'],
  Shoulders: ['Anterior', 'Lateral', 'Posterior'],
  Arms: ['Biceps', 'Triceps', 'Forearms'],
  Legs: ['Quads', 'Hamstrings', 'Glutes', 'Calves'],
  Core: ['Abs', 'Obliques'],
};

export const TYPES = {
  wr: 'Weight and reps',
  r: 'Reps only',
  t: 'Time',
  dt: 'Distance and time',
};

// E(id, name, group, sub, equip, type, desc). The label shown is "Name · Equipment" (see exLabel in seteditor.js).
// Order within a group is the display order. Ids never change (saved logs refer to them) – add new ones instead.
const E = (id, name, group, sub, equip, type, desc = '') => ({ id, name, group, sub, equip, type, desc, builtin: true });

export const EXERCISES = [
  // ---------- Chest (Upper / Middle / Lower) ----------
  E('bench-press', 'Bench Press', 'Chest', 'Middle', 'Barbell', 'wr', 'Lie on the bench, lower the bar under control to your chest and press up to straight arms. Keep your shoulder blades retracted.'),
  E('db-bench-press', 'Bench Press', 'Chest', 'Middle', 'Dumbbell', 'wr', 'Press the dumbbells up from your chest. Allows a greater range of motion than a barbell.'),
  E('cable-bench-press', 'Bench Press', 'Chest', 'Middle', 'Cable', 'wr', 'Bench press with a cable on each side for constant tension.'),
  E('smith-bench-press', 'Bench Press', 'Chest', 'Middle', 'Smith Machine', 'wr', 'Bench press in the Smith machine – a fixed bar path lets you focus on pushing.'),
  E('incline-bench-press', 'Incline Bench Press', 'Chest', 'Upper', 'Barbell', 'wr', 'Bench press on an incline bench (30–45°) to emphasise the upper chest.'),
  E('db-incline-press', 'Incline Bench Press', 'Chest', 'Upper', 'Dumbbell', 'wr', 'Dumbbell press on an incline bench for the upper chest and front delts.'),
  E('cable-incline-press', 'Incline Bench Press', 'Chest', 'Upper', 'Cable', 'wr', 'Incline press with cables from low pulleys.'),
  E('smith-incline-press', 'Incline Bench Press', 'Chest', 'Upper', 'Smith Machine', 'wr', 'Incline bench press in the Smith machine.'),
  E('decline-bench-press', 'Decline Bench Press', 'Chest', 'Lower', 'Barbell', 'wr', 'Bench press with your head lower than your hips. Targets the lower chest.'),
  E('db-decline-press', 'Decline Bench Press', 'Chest', 'Lower', 'Dumbbell', 'wr', 'Decline press with dumbbells for the lower chest.'),
  E('cable-decline-press', 'Decline Bench Press', 'Chest', 'Lower', 'Cable', 'wr', 'Decline press with cables from high pulleys.'),
  E('smith-decline-press', 'Decline Bench Press', 'Chest', 'Lower', 'Smith Machine', 'wr', 'Decline bench press in the Smith machine.'),
  E('plate-loaded-press', 'Plate-Loaded Chest Press', 'Chest', 'Middle', 'Machine', 'wr', 'Seated chest press on a plate-loaded machine with independent arms.'),
  E('machine-chest-press', 'Chest Press', 'Chest', 'Middle', 'Machine', 'wr', 'Seated press in a machine. A safe option for training heavy.'),
  E('standing-cable-press', 'Standing Chest Press', 'Chest', 'Middle', 'Cable', 'wr', 'Stand between the cables and press forward at chest height.'),
  E('db-flyes', 'Chest Fly', 'Chest', 'Middle', 'Dumbbell', 'wr', 'With a slight bend in the elbows, lower your arms out to the sides in an arc and bring them together over your chest.'),
  E('incline-db-fly', 'Incline Chest Fly', 'Chest', 'Upper', 'Dumbbell', 'wr', 'Dumbbell flyes on an incline bench for the upper chest.'),
  E('decline-db-fly', 'Decline Chest Fly', 'Chest', 'Lower', 'Dumbbell', 'wr', 'Dumbbell flyes on a decline bench for the lower chest.'),
  E('cable-crossover', 'Standing Chest Fly', 'Chest', 'Middle', 'Cable', 'wr', 'Pull the handles down and together in front of your body in an arc.'),
  E('pec-deck', 'Pec Deck', 'Chest', 'Middle', 'Machine', 'wr', 'Bring your arms together in front of your chest in the machine.'),
  E('machine-fly', 'Chest Fly', 'Chest', 'Middle', 'Machine', 'wr', 'Fly movement in a chest fly machine with straight arms.'),
  E('cable-fly', 'Chest Fly', 'Chest', 'Middle', 'Cable', 'wr', 'Lying on a bench between two low pulleys, bring the handles together over your chest.'),
  E('incline-cable-fly', 'Incline Chest Fly', 'Chest', 'Upper', 'Cable', 'wr', 'Cable flyes on an incline bench, or from low to high pulleys.'),
  E('decline-cable-fly', 'Decline Chest Fly', 'Chest', 'Lower', 'Cable', 'wr', 'Cable flyes from high to low for the lower chest.'),
  E('barbell-pullover', 'Pullover', 'Chest', 'Middle', 'Barbell', 'wr', 'Lying across or along the bench, lower the bar behind your head with slightly bent arms and pull it back.'),
  E('pullover', 'Pullover', 'Chest', 'Middle', 'Dumbbell', 'wr', 'Lie across the bench and move the dumbbell behind your head and back.'),
  E('cable-pullover', 'Pullover', 'Chest', 'Middle', 'Cable', 'wr', 'Pullover with a rope or bar from a cable behind you.'),
  E('machine-pullover', 'Pullover', 'Chest', 'Middle', 'Machine', 'wr', 'Pullover in a pullover machine.'),
  E('push-ups', 'Push Up', 'Chest', 'Middle', 'Bodyweight', 'r', 'Body straight from head to heels, lower your chest to the floor and push back up.'),
  E('incline-push-up', 'Incline Push Up', 'Chest', 'Lower', 'Bodyweight', 'r', 'Push-ups with your hands on a bench – easier, and more lower chest.'),
  E('decline-push-up', 'Decline Push Up', 'Chest', 'Upper', 'Bodyweight', 'r', 'Push-ups with your feet on a bench – harder, and more upper chest.'),
  E('dips', 'Chest Dip', 'Chest', 'Lower', 'Bodyweight', 'r', 'Lower yourself between parallel bars with a forward lean and press back up.'),
  E('lying-around-the-world', 'Lying Around the World', 'Chest', 'Middle', 'Dumbbell', 'wr', 'Lying on a bench, move light dumbbells in a wide arc from your hips to over your head and back.'),
  E('band-chest-press', 'Chest Press', 'Chest', 'Middle', 'Band', 'r', 'Anchor the band behind you and press forward at chest height.'),
  E('band-flyes', 'Chest Fly', 'Chest', 'Middle', 'Band', 'r', 'With the band anchored behind you, bring your arms together in front of your chest.'),

  // ---------- Back (Lats / Upper back / Lower back / Traps) ----------
  E('deadlift', 'Deadlift', 'Back', 'Lower back', 'Barbell', 'wr', 'Bar over mid-foot, neutral spine. Lift by pushing the floor away and extending your hips.'),
  E('pull-ups', 'Pull Up', 'Back', 'Lats', 'Bodyweight', 'r', 'Overhand grip, pull yourself up until your chin is over the bar.'),
  E('lat-pulldown', 'Lat Pulldown', 'Back', 'Lats', 'Cable', 'wr', 'Pull the bar down to your upper chest with your chest up.'),
  E('machine-pulldown', 'Lat Pulldown', 'Back', 'Lats', 'Machine', 'wr', 'Pulldown in a plate-loaded or selectorised machine.'),
  E('straight-arm-pulldown', 'Straight Arm Pulldown', 'Back', 'Lats', 'Cable', 'wr', 'With straight arms, pull the bar or rope from overhead down to your thighs.'),
  E('barbell-row', 'Bent Over Row', 'Back', 'Upper back', 'Barbell', 'wr', 'Bent over with a flat back, pull the bar towards your belly button.'),
  E('db-row', 'One Arm Row', 'Back', 'Lats', 'Dumbbell', 'wr', 'One hand and one knee on the bench, pull the dumbbell towards your hip.'),
  E('seated-cable-row', 'Seated Row', 'Back', 'Upper back', 'Cable', 'wr', 'Pull the handle towards your stomach and squeeze your shoulder blades together.'),
  E('machine-row', 'Seated Row', 'Back', 'Upper back', 'Machine', 'wr', 'Chest-supported row in a machine.'),
  E('t-bar-row', 'T-Bar Row', 'Back', 'Upper back', 'Machine', 'wr', 'Row with a T-bar or landmine for a thick back.'),
  E('back-extension', 'Hyperextension', 'Back', 'Lower back', 'Bodyweight', 'r', 'On a back extension bench, lower your upper body and raise it to a straight line.'),
  E('good-morning', 'Good Morning', 'Back', 'Lower back', 'Barbell', 'wr', 'Bar on your upper back, hinge forward at the hips with a flat back and stand back up.'),
  E('shrugs', 'Shrug', 'Back', 'Traps', 'Dumbbell', 'wr', 'Raise your shoulders straight up towards your ears and lower under control.'),
  E('barbell-shrug', 'Shrug', 'Back', 'Traps', 'Barbell', 'wr', 'Shrug with a barbell held in front of your thighs.'),
  E('band-row', 'Row', 'Back', 'Upper back', 'Band', 'r', 'With the band anchored in front of you, pull the handles towards your stomach.'),
  E('band-pulldown', 'Pulldown', 'Back', 'Lats', 'Band', 'r', 'With the band anchored high, pull down towards your chest.'),
  E('band-pull-apart', 'Pull-Apart', 'Back', 'Upper back', 'Band', 'r', 'Hold the band in front of you at shoulder height and pull it apart.'),

  // ---------- Shoulders (Anterior / Lateral / Posterior) ----------
  E('overhead-press', 'Overhead Press', 'Shoulders', 'Anterior', 'Barbell', 'wr', 'Press the bar from your shoulders to overhead with a tight core.'),
  E('db-shoulder-press', 'Overhead Press', 'Shoulders', 'Anterior', 'Dumbbell', 'wr', 'Standing press with dumbbells.'),
  E('cable-ohp', 'Overhead Press', 'Shoulders', 'Anterior', 'Cable', 'wr', 'Overhead press with cables from low pulleys.'),
  E('machine-shoulder-press', 'Overhead Press', 'Shoulders', 'Anterior', 'Machine', 'wr', 'Seated press in a shoulder press machine.'),
  E('smith-ohp', 'Overhead Press', 'Shoulders', 'Anterior', 'Smith Machine', 'wr', 'Seated or standing overhead press in the Smith machine.'),
  E('seated-ohp-barbell', 'Seated Overhead Press', 'Shoulders', 'Anterior', 'Barbell', 'wr', 'Overhead press sitting on an upright bench.'),
  E('seated-ohp-db', 'Seated Overhead Press', 'Shoulders', 'Anterior', 'Dumbbell', 'wr', 'Dumbbell shoulder press sitting on an upright bench.'),
  E('btn-press', 'Behind The Neck Overhead Press', 'Shoulders', 'Anterior', 'Smith Machine', 'wr', 'Press from behind the neck in the Smith machine. Only with good shoulder mobility.'),
  E('arnold-press', 'Arnold Press', 'Shoulders', 'Anterior', 'Dumbbell', 'wr', 'Shoulder press with a rotation of the wrists through the movement.'),
  E('cuban-press', 'Cuban Press', 'Shoulders', 'Posterior', 'Dumbbell', 'wr', 'Upright row, rotate the forearms up, then press overhead. Light weights for rotator cuff strength.'),
  E('cable-reverse-fly', 'Reverse Fly', 'Shoulders', 'Posterior', 'Cable', 'wr', 'Cross the cables and pull your arms out and back at shoulder height.'),
  E('machine-reverse-fly', 'Reverse Fly', 'Shoulders', 'Posterior', 'Machine', 'wr', 'Reverse fly facing the pec deck machine.'),
  E('lying-reverse-fly', 'Lying Reverse Fly', 'Shoulders', 'Posterior', 'Dumbbell', 'wr', 'Lying face down on an incline bench, raise the dumbbells out to the sides.'),
  E('reverse-flyes', 'Bent Over Reverse Fly', 'Shoulders', 'Posterior', 'Dumbbell', 'wr', 'Bent over, raise your arms out to the sides for the rear delts.'),
  E('bent-cable-reverse-fly', 'Bent Over Reverse Fly', 'Shoulders', 'Posterior', 'Cable', 'wr', 'Bent over between two low pulleys, pull the handles out to the sides.'),
  E('lateral-raise', 'Lateral Raise', 'Shoulders', 'Lateral', 'Dumbbell', 'wr', 'Raise the dumbbells out to the sides to shoulder height with a slight bend in the elbow.'),
  E('cable-lateral-raise', 'Lateral Raise', 'Shoulders', 'Lateral', 'Cable', 'wr', 'One arm at a time from a low pulley, raise out to the side.'),
  E('machine-lateral-raise', 'Lateral Raise', 'Shoulders', 'Lateral', 'Machine', 'wr', 'Lateral raise in a machine.'),
  E('front-raise-barbell', 'Front Raise', 'Shoulders', 'Anterior', 'Barbell', 'wr', 'Raise the bar straight in front of you to shoulder height.'),
  E('front-raise', 'Front Raise', 'Shoulders', 'Anterior', 'Dumbbell', 'wr', 'Raise the dumbbells straight in front of you to shoulder height.'),
  E('plate-front-raise', 'Front Raise', 'Shoulders', 'Anterior', 'Plate', 'wr', 'Hold a weight plate with both hands and raise it to eye level.'),
  E('cable-front-raise', 'Front Raise', 'Shoulders', 'Anterior', 'Cable', 'wr', 'Front raise from a low pulley.'),
  E('upright-row', 'Upright Row', 'Shoulders', 'Lateral', 'Barbell', 'wr', 'Pull the bar up along your body to chest height.'),
  E('db-upright-row', 'Upright Row', 'Shoulders', 'Lateral', 'Dumbbell', 'wr', 'Upright row with dumbbells.'),
  E('cable-upright-row', 'Upright Row', 'Shoulders', 'Lateral', 'Cable', 'wr', 'Upright row with a bar on a low pulley.'),
  E('smith-upright-row', 'Upright Row', 'Shoulders', 'Lateral', 'Smith Machine', 'wr', 'Upright row in the Smith machine.'),
  E('cable-rear-delt-row', 'Rear Delt Row', 'Shoulders', 'Posterior', 'Cable', 'wr', 'Row to your face with elbows high and out to the sides.'),
  E('bent-rear-delt-row-barbell', 'Bent Over Rear Delt Row', 'Shoulders', 'Posterior', 'Barbell', 'wr', 'Bent over row to your upper chest with elbows flared.'),
  E('bent-rear-delt-row-db', 'Bent Over Rear Delt Row', 'Shoulders', 'Posterior', 'Dumbbell', 'wr', 'Bent over dumbbell row with elbows flared.'),
  E('bent-rear-delt-row-smith', 'Bent Over Rear Delt Row', 'Shoulders', 'Posterior', 'Smith Machine', 'wr', 'Rear delt row in the Smith machine.'),
  E('face-pull', 'Face Pull', 'Shoulders', 'Posterior', 'Cable', 'wr', 'Pull the rope towards your face with your elbows high.'),
  E('standing-around-world', 'Standing Around the World', 'Shoulders', 'Lateral', 'Dumbbell', 'wr', 'Standing, move light dumbbells in a wide arc from your thighs to overhead and back.'),
  E('incline-around-world', 'Incline Around the World', 'Shoulders', 'Anterior', 'Dumbbell', 'wr', 'Lying face down on an incline bench, move the dumbbells in a wide arc.'),
  E('internal-rotation', 'Internal Rotation', 'Shoulders', 'Anterior', 'Cable', 'wr', 'Elbow at your side at 90°, rotate the forearm in towards your stomach.'),
  E('external-rotation', 'External Rotation', 'Shoulders', 'Posterior', 'Cable', 'wr', 'Elbow at your side at 90°, rotate the forearm out away from your body.'),
  E('pike-push-up', 'Pike Push Up', 'Shoulders', 'Anterior', 'Bodyweight', 'r', 'Hips high in an upside-down V, lower your head towards the floor and push up.'),
  E('handstand-push-up', 'Handstand Push Up', 'Shoulders', 'Anterior', 'Bodyweight', 'r', 'In a handstand against a wall, lower your head to the floor and press back up.'),
  E('band-shoulder-press', 'Overhead Press', 'Shoulders', 'Anterior', 'Band', 'r', 'Stand on the band and press the handles overhead.'),
  E('band-lateral-raise', 'Lateral Raise', 'Shoulders', 'Lateral', 'Band', 'r', 'Stand on the band and raise your arms out to the sides.'),

  // ---------- Arms (Biceps / Triceps / Forearms) ----------
  E('barbell-curl', 'Curl', 'Arms', 'Biceps', 'Barbell', 'wr', 'Standing curl with your elbows tucked in to your sides.'),
  E('db-curl', 'Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Curl with supination of the wrist at the top.'),
  E('cable-curl', 'Curl', 'Arms', 'Biceps', 'Cable', 'wr', 'Curl with constant tension from a cable.'),
  E('machine-curl', 'Curl', 'Arms', 'Biceps', 'Machine', 'wr', 'Curl in a biceps machine.'),
  E('incline-db-curl', 'Incline Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Sitting on an incline bench with arms hanging behind you, curl the dumbbells.'),
  E('pinwheel-curl', 'Pinwheel Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Curl the dumbbell across your body towards the opposite shoulder.'),
  E('supinating-curl', 'Supinating Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Start with a neutral grip and rotate your palm up as you curl.'),
  E('zottman-curl', 'Zottman Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Curl up with palms up, rotate to palms down at the top and lower slowly.'),
  E('spider-curl-barbell', 'Spider Curl', 'Arms', 'Biceps', 'Barbell', 'wr', 'Chest against an incline bench, arms hanging straight down, curl the bar.'),
  E('spider-curl-db', 'Spider Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Chest against an incline bench, arms hanging straight down, curl the dumbbells.'),
  E('hammer-curl', 'Hammer Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Curl with a neutral grip (thumbs up).'),
  E('cable-hammer-curl', 'Hammer Curl', 'Arms', 'Biceps', 'Cable', 'wr', 'Hammer curl with a rope on a low pulley.'),
  E('concentration-curl-barbell', 'Concentration Curl', 'Arms', 'Biceps', 'Barbell', 'wr', 'Leaning forward with elbows braced on your thighs, curl a short bar.'),
  E('concentration-curl', 'Concentration Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Seated, elbow braced against the inside of your thigh.'),
  E('cable-concentration-curl', 'Concentration Curl', 'Arms', 'Biceps', 'Cable', 'wr', 'Concentration curl with a single handle on a low pulley.'),
  E('reverse-grip-pulldown', 'Lat Pull Down (Reverse Grip)', 'Arms', 'Biceps', 'Cable', 'wr', 'Pulldown with an underhand, shoulder-width grip for the biceps and lats.'),
  E('chin-ups', 'Chin Up', 'Arms', 'Biceps', 'Bodyweight', 'r', 'Underhand grip, pull yourself up until your chin is over the bar.'),
  E('wide-chin-up', 'Chin Up (Wide Grip)', 'Arms', 'Biceps', 'Bodyweight', 'r', 'Chin-up with an underhand grip wider than your shoulders.'),
  E('close-chin-up', 'Chin Up (Close Grip)', 'Arms', 'Biceps', 'Bodyweight', 'r', 'Chin-up with your hands close together.'),
  E('preacher-curl', 'Preacher Curl', 'Arms', 'Biceps', 'Barbell', 'wr', 'Curl with your upper arms resting on an angled pad.'),
  E('db-preacher-curl', 'Preacher Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Preacher curl with dumbbells.'),
  E('cable-preacher-curl', 'Preacher Curl', 'Arms', 'Biceps', 'Cable', 'wr', 'Preacher curl with a bar on a low pulley.'),
  E('machine-preacher-curl', 'Preacher Curl', 'Arms', 'Biceps', 'Machine', 'wr', 'Preacher curl in a biceps machine.'),
  E('single-arm-preacher-curl', 'Single Arm Preacher Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Preacher curl one arm at a time.'),
  E('preacher-hammer-curl', 'Preacher Hammer Curl', 'Arms', 'Biceps', 'Dumbbell', 'wr', 'Preacher curl with a neutral grip.'),
  E('band-curl', 'Curl', 'Arms', 'Biceps', 'Band', 'r', 'Stand on the band and curl the handles up.'),
  E('close-grip-bench', 'Bench Press (Close Grip)', 'Arms', 'Triceps', 'Barbell', 'wr', 'Bench press with a shoulder-width grip for the triceps.'),
  E('db-close-grip-bench', 'Bench Press (Close Grip)', 'Arms', 'Triceps', 'Dumbbell', 'wr', 'Dumbbell press with the dumbbells touching and elbows tucked.'),
  E('smith-close-grip-bench', 'Bench Press (Close Grip)', 'Arms', 'Triceps', 'Smith Machine', 'wr', 'Close-grip bench press in the Smith machine.'),
  E('skull-crusher', 'Lying Tricep Extension', 'Arms', 'Triceps', 'Barbell', 'wr', 'Lying down, lower the bar towards your forehead and extend your arms.'),
  E('db-lying-tricep-extension', 'Lying Tricep Extension', 'Arms', 'Triceps', 'Dumbbell', 'wr', 'Lying down, lower the dumbbells beside your head and extend your arms.'),
  E('cable-lying-tricep-extension', 'Lying Tricep Extension', 'Arms', 'Triceps', 'Cable', 'wr', 'Lying tricep extension with a bar from a low pulley behind your head.'),
  E('seated-oh-ext-barbell', 'Seated Overhead Tricep Extension', 'Arms', 'Triceps', 'Barbell', 'wr', 'Seated, lower the bar behind your head and extend.'),
  E('seated-oh-ext-db', 'Seated Overhead Tricep Extension', 'Arms', 'Triceps', 'Dumbbell', 'wr', 'Seated, hold one dumbbell with both hands, lower it behind your head and extend.'),
  E('single-arm-oh-ext', 'Single Arm Overhead Triceps Extension', 'Arms', 'Triceps', 'Dumbbell', 'wr', 'One arm at a time, lower the dumbbell behind your head and extend.'),
  E('overhead-triceps-extension', 'Overhead Tricep Extension', 'Arms', 'Triceps', 'Dumbbell', 'wr', 'Standing, hold the dumbbell overhead, lower it behind your neck and extend.'),
  E('cable-overhead-extension', 'Overhead Tricep Extension', 'Arms', 'Triceps', 'Cable', 'wr', 'Facing away from the pulley, extend the rope overhead.'),
  E('kneeling-oh-ext-cable', 'Kneeling Overhead Tricep Extension', 'Arms', 'Triceps', 'Cable', 'wr', 'Kneeling facing away from the pulley, extend the rope overhead.'),
  E('triceps-pushdown', 'Tricep Extension', 'Arms', 'Triceps', 'Cable', 'wr', 'Push the bar or rope down with your elbows tucked in to your sides.'),
  E('machine-tricep-extension', 'Tricep Extension', 'Arms', 'Triceps', 'Machine', 'wr', 'Extend your arms in a triceps machine.'),
  E('triceps-kickback', 'Tricep Kickback', 'Arms', 'Triceps', 'Dumbbell', 'wr', 'Bent over, extend your arm backwards.'),
  E('cable-tricep-kickback', 'Tricep Kickback', 'Arms', 'Triceps', 'Cable', 'wr', 'Kickback with a single handle from a low pulley.'),
  E('tricep-dip', 'Tricep Dip', 'Arms', 'Triceps', 'Bodyweight', 'r', 'Upright dips on parallel bars for the triceps.'),
  E('machine-dip', 'Tricep Dip', 'Arms', 'Triceps', 'Machine', 'wr', 'Seated dip machine.'),
  E('bench-dips', 'Bench Dip', 'Arms', 'Triceps', 'Bodyweight', 'r', 'Hands on the bench behind you, lower and press back up.'),
  E('bodyweight-tricep-extension', 'Bodyweight Tricep Extension', 'Arms', 'Triceps', 'Bodyweight', 'r', 'Hands on a bar or bench, lower your forehead below your hands and extend.'),
  E('diamond-push-ups', 'Diamond Push Up', 'Arms', 'Triceps', 'Bodyweight', 'r', 'Push-ups with your hands close together under your chest.'),
  E('side-push-up', 'Side Push Up', 'Arms', 'Triceps', 'Bodyweight', 'r', 'Lying on your side, push your upper body up with one arm.'),
  E('band-triceps-extension', 'Tricep Extension', 'Arms', 'Triceps', 'Band', 'r', 'With the band anchored high, push down with your elbows tucked in.'),
  E('reverse-curl', 'Reverse Curl', 'Arms', 'Forearms', 'Barbell', 'wr', 'Curl with an overhand grip for the forearms.'),
  E('db-reverse-curl', 'Reverse Curl', 'Arms', 'Forearms', 'Dumbbell', 'wr', 'Reverse curl with dumbbells.'),
  E('cable-reverse-curl', 'Reverse Curl', 'Arms', 'Forearms', 'Cable', 'wr', 'Reverse curl with a bar on a low pulley.'),
  E('reverse-concentration-curl', 'Reverse Concentration Curl', 'Arms', 'Forearms', 'Dumbbell', 'wr', 'Concentration curl with an overhand grip.'),
  E('wrist-curl-barbell', 'Wrist Curl', 'Arms', 'Forearms', 'Barbell', 'wr', 'Forearms on a bench, curl the bar with your wrists only.'),
  E('wrist-curl', 'Wrist Curl', 'Arms', 'Forearms', 'Dumbbell', 'wr', 'Forearms on the bench, curl with the wrist only.'),
  E('cable-wrist-curl', 'Wrist Curl', 'Arms', 'Forearms', 'Cable', 'wr', 'Wrist curl with a bar on a low pulley.'),
  E('behind-back-wrist-curl', 'Behind the Back Wrist Curl', 'Arms', 'Forearms', 'Barbell', 'wr', 'Hold the bar behind your back and curl it with your wrists.'),
  E('dead-hang', 'Dead Hang', 'Arms', 'Forearms', 'Bodyweight', 't', 'Hang from the bar with straight arms for as long as you can.'),

  // ---------- Legs (Quads / Hamstrings / Glutes / Calves) ----------
  E('squat', 'Squat', 'Legs', 'Quads', 'Barbell', 'wr', 'Bar on your upper back, sit down to at least parallel and stand back up.'),
  E('smith-squat', 'Squat', 'Legs', 'Quads', 'Smith Machine', 'wr', 'Squat in the Smith machine with feet slightly forward.'),
  E('front-squat', 'Front Squat', 'Legs', 'Quads', 'Barbell', 'wr', 'Bar racked on the front of your shoulders, upright torso.'),
  E('goblet-squat', 'Goblet Squat', 'Legs', 'Quads', 'Kettlebell', 'wr', 'Hold a kettlebell in front of your chest and squat.'),
  E('hack-squat', 'Hack Squat', 'Legs', 'Quads', 'Machine', 'wr', 'Squat in a hack squat machine.'),
  E('leg-press', 'Leg Press', 'Legs', 'Quads', 'Machine', 'wr', 'Push the platform away without fully locking your knees.'),
  E('leg-extension', 'Leg Extension', 'Legs', 'Quads', 'Machine', 'wr', 'Extend your knees in a machine for the quads.'),
  E('lunges', 'Lunge', 'Legs', 'Quads', 'Dumbbell', 'wr', 'Take a long step forward and lower your back knee towards the floor.'),
  E('barbell-lunge', 'Lunge', 'Legs', 'Quads', 'Barbell', 'wr', 'Lunges with a barbell on your upper back.'),
  E('bulgarian-split-squat', 'Bulgarian Split Squat', 'Legs', 'Quads', 'Dumbbell', 'wr', 'Rear foot on a bench, lower yourself on the front leg.'),
  E('step-up', 'Step Up', 'Legs', 'Quads', 'Dumbbell', 'wr', 'Step up onto a box or bench one leg at a time.'),
  E('bodyweight-squat', 'Squat', 'Legs', 'Quads', 'Bodyweight', 'r', 'Squat using only your bodyweight.'),
  E('wall-sit', 'Wall Sit', 'Legs', 'Quads', 'Bodyweight', 't', 'Sit with your back against the wall and knees at 90°.'),
  E('band-squat', 'Squat', 'Legs', 'Quads', 'Band', 'r', 'Stand on the band with the handles at your shoulders and squat.'),
  E('romanian-deadlift', 'Romanian Deadlift', 'Legs', 'Hamstrings', 'Barbell', 'wr', 'Slight bend in the knees, push your hips back and lower the bar along your legs.'),
  E('db-romanian-deadlift', 'Romanian Deadlift', 'Legs', 'Hamstrings', 'Dumbbell', 'wr', 'Romanian deadlift with dumbbells.'),
  E('leg-curl', 'Leg Curl', 'Legs', 'Hamstrings', 'Machine', 'wr', 'Bend your knees in a machine for the hamstrings.'),
  E('lying-leg-curl-db', 'Lying Leg Curl', 'Legs', 'Hamstrings', 'Dumbbell', 'wr', 'Lying face down, hold a dumbbell between your feet and curl it up.'),
  E('nordic-curl', 'Nordic Curl', 'Legs', 'Hamstrings', 'Bodyweight', 'r', 'Kneeling with your feet held, lower your body forward as slowly as possible.'),
  E('hip-thrust', 'Hip Thrust', 'Legs', 'Glutes', 'Barbell', 'wr', 'Upper back against the bench, bar over your hips, drive your hips up.'),
  E('machine-hip-thrust', 'Hip Thrust', 'Legs', 'Glutes', 'Machine', 'wr', 'Hip thrust in a glute machine.'),
  E('glute-bridge', 'Glute Bridge', 'Legs', 'Glutes', 'Bodyweight', 'r', 'Lie on your back and lift your hips towards the ceiling.'),
  E('cable-kickback', 'Glute Kickback', 'Legs', 'Glutes', 'Cable', 'wr', 'Kick your leg backwards against cable resistance.'),
  E('hip-abduction', 'Hip Abduction', 'Legs', 'Glutes', 'Machine', 'wr', 'Push your knees out against resistance.'),
  E('hip-adduction', 'Hip Adduction', 'Legs', 'Quads', 'Machine', 'wr', 'Squeeze your knees together against resistance (inner thighs).'),
  E('band-lateral-walk', 'Lateral Walk', 'Legs', 'Glutes', 'Band', 'r', 'Band around your knees, walk sideways in a half squat.'),
  E('band-glute-bridge', 'Glute Bridge', 'Legs', 'Glutes', 'Band', 'r', 'Glute bridge with a band around your knees, pushing the knees out.'),
  E('standing-calf-raise', 'Standing Calf Raise', 'Legs', 'Calves', 'Machine', 'wr', 'Rise up onto your toes and lower slowly.'),
  E('seated-calf-raise', 'Seated Calf Raise', 'Legs', 'Calves', 'Machine', 'wr', 'Seated calf raise for the soleus.'),
  E('calf-press', 'Calf Press', 'Legs', 'Calves', 'Machine', 'wr', 'Calf raise on the leg press platform.'),
  E('bodyweight-calf-raise', 'Calf Raise', 'Legs', 'Calves', 'Bodyweight', 'r', 'Calf raise on a step using your own bodyweight.'),

  // ---------- Core (Abs / Obliques) ----------
  E('plank', 'Plank', 'Core', 'Abs', 'Bodyweight', 't', 'Hold your body straight on your forearms and toes.'),
  E('side-plank', 'Side Plank', 'Core', 'Obliques', 'Bodyweight', 't', 'Plank on your side with your hips raised.'),
  E('crunches', 'Crunch', 'Core', 'Abs', 'Bodyweight', 'r', 'Lift your shoulders off the floor by curling your upper body.'),
  E('cable-crunch', 'Crunch', 'Core', 'Abs', 'Cable', 'wr', 'Kneeling, curl your upper body down against cable resistance.'),
  E('machine-crunch', 'Crunch', 'Core', 'Abs', 'Machine', 'wr', 'Crunch in an ab machine.'),
  E('sit-ups', 'Sit Up', 'Core', 'Abs', 'Bodyweight', 'r', 'Roll up from lying to sitting.'),
  E('hanging-leg-raise', 'Hanging Leg Raise', 'Core', 'Abs', 'Bodyweight', 'r', 'Hang from the bar and raise your legs in front of you.'),
  E('lying-leg-raise', 'Lying Leg Raise', 'Core', 'Abs', 'Bodyweight', 'r', 'Lying on your back, raise straight legs to vertical and lower slowly.'),
  E('ab-wheel', 'Ab Wheel Rollout', 'Core', 'Abs', 'Other', 'r', 'Roll the wheel forward from your knees and pull it back.'),
  E('dead-bug', 'Dead Bug', 'Core', 'Abs', 'Bodyweight', 'r', 'Lie on your back, extend opposite arm and leg while keeping your lower back on the floor.'),
  E('russian-twist', 'Russian Twist', 'Core', 'Obliques', 'Bodyweight', 'r', 'Sit leaning back and rotate your upper body from side to side.'),
  E('cable-woodchop', 'Woodchop', 'Core', 'Obliques', 'Cable', 'wr', 'Rotate and pull the cable diagonally across your body.'),
  E('pallof-press', 'Pallof Press', 'Core', 'Obliques', 'Band', 'r', 'Band anchored to the side, press straight out and resist rotation.'),

  // ---------- Full-Body ----------
  E('kettlebell-swing', 'Swing', 'Full-Body', '', 'Kettlebell', 'wr', 'Explosive hip hinge that swings the kettlebell to chest height.'),
  E('turkish-get-up', 'Turkish Get Up', 'Full-Body', '', 'Kettlebell', 'wr', 'Get up from lying to standing with a kettlebell overhead.'),
  E('farmers-walk', 'Farmer\'s Walk', 'Full-Body', '', 'Dumbbell', 'dt', 'Walk while holding heavy dumbbells or kettlebells.'),
  E('iron-cross', 'Iron Cross', 'Full-Body', '', 'Dumbbell', 'wr', 'Squat while raising light dumbbells to the front and out to the sides.'),
  E('squat-row', 'Squat Row', 'Full-Body', '', 'Cable', 'wr', 'Squat down, then stand up while rowing the cable to your stomach.'),
  E('renegade-row', 'Renegade Row', 'Full-Body', '', 'Dumbbell', 'wr', 'In a push-up position on two dumbbells, row one at a time.'),
  E('thruster-barbell', 'Thruster', 'Full-Body', '', 'Barbell', 'wr', 'A front squat that flows straight into an overhead press.'),
  E('thrusters', 'Thruster', 'Full-Body', '', 'Dumbbell', 'wr', 'A dumbbell front squat that flows straight into a shoulder press.'),
  E('thruster-kb', 'Thruster', 'Full-Body', '', 'Kettlebell', 'wr', 'Thruster with kettlebells racked at your shoulders.'),
  E('clean', 'Clean', 'Full-Body', '', 'Barbell', 'wr', 'Lift the bar explosively from the floor and catch it on your shoulders in a squat.'),
  E('power-clean', 'Power Clean', 'Full-Body', '', 'Barbell', 'wr', 'Explosive lift of the bar from the floor to your shoulders, caught high.'),
  E('clean-and-jerk', 'Clean & Jerk', 'Full-Body', '', 'Barbell', 'wr', 'Clean the bar to your shoulders, then drive it overhead.'),
  E('snatch', 'Snatch', 'Full-Body', '', 'Barbell', 'wr', 'Lift the bar from the floor to overhead in one explosive movement.'),
  E('deadlift-high-pull', 'Deadlift High Pull', 'Full-Body', '', 'Barbell', 'wr', 'Deadlift that finishes with an explosive pull to chest height.'),
  E('muscle-up', 'Muscle Up', 'Full-Body', '', 'Bodyweight', 'r', 'Explosive pull-up that transitions to a dip above the bar.'),
  E('gorilla-chin-crunch', 'Gorilla Chin Crunch', 'Full-Body', '', 'Bodyweight', 'r', 'Chin-up while bringing your knees up to your chest.'),
  E('wall-ball', 'Wall Ball', 'Full-Body', '', 'Other', 'r', 'Squat with a medicine ball and throw it to a target on the wall.'),
  E('slam-ball', 'Slam Ball', 'Full-Body', '', 'Other', 'r', 'Lift a slam ball overhead and throw it hard into the floor.'),
  E('box-jumps', 'Box Jump', 'Full-Body', '', 'Other', 'r', 'Jump up onto a stable box and step down.'),

  // ---------- Cardio ----------
  E('walking', 'Walking', 'Cardio', '', 'Other', 'dt', 'Brisk walking outdoors or on a treadmill.'),
  E('running', 'Running', 'Cardio', '', 'Other', 'dt', 'Running outdoors.'),
  E('treadmill', 'Treadmill', 'Cardio', '', 'Machine', 'dt', 'Walking or running on a treadmill.'),
  E('elliptical', 'Elliptical', 'Cardio', '', 'Machine', 'dt', 'Low-impact cardio on an elliptical trainer.'),
  E('cycling', 'Bicycle', 'Cardio', '', 'Machine', 'dt', 'Spin bike, ergometer or outdoors.'),
  E('stepper', 'Stepper', 'Cardio', '', 'Machine', 't', 'Step on a stepper machine.'),
  E('stair-climber', 'Stair Climber', 'Cardio', '', 'Machine', 't', 'Climb on a stair machine.'),
  E('jump-rope', 'Jump Rope', 'Cardio', '', 'Other', 't', 'Skip rope at a steady pace.'),
  E('rowing-machine', 'Rowing', 'Cardio', '', 'Machine', 'dt', 'Rowing on an ergometer.'),
  E('swimming', 'Swimming', 'Cardio', '', 'Other', 'dt', 'Swimming in a pool or open water.'),
  E('battle-rope', 'Battle Rope', 'Cardio', '', 'Other', 't', 'Make waves with heavy ropes as fast as you can.'),
  E('burpees', 'Burpee', 'Cardio', '', 'Bodyweight', 'r', 'Squat, kick your legs back, push-up, jump forward and jump up.'),
  E('squat-jump', 'Squat Jump', 'Cardio', '', 'Bodyweight', 'r', 'Squat down and jump as high as you can.'),
  E('mountain-climbers', 'Mountain Climber', 'Cardio', '', 'Bodyweight', 'r', 'In a push-up position, drive your knees alternately towards your chest at a fast pace.'),
  E('jumping-jacks', 'Jumping Jack', 'Cardio', '', 'Bodyweight', 'r', 'Jump out with arms and legs at the same time and back.'),
  E('frogger', 'Frogger', 'Cardio', '', 'Bodyweight', 'r', 'From a plank, jump your feet up outside your hands and back.'),
  E('lunge-jump', 'Lunge Jump', 'Cardio', '', 'Bodyweight', 'r', 'Jump and switch legs in a lunge position.'),
  E('high-knee-skip', 'High Knee Skip', 'Cardio', '', 'Bodyweight', 't', 'Skip forward driving your knees high.'),
  E('butt-kicks', 'Butt Kicks', 'Cardio', '', 'Bodyweight', 't', 'Jog in place kicking your heels up to your glutes.'),
];

const W = (name, exercises) => ({ name, exercises: exercises.map(([ex, sets, reps]) => ({ ex, sets, reps })) });

export const PROGRAMS = [
  {
    id: 'p-full-body',
    name: 'Full Body for Beginners',
    level: 'Beginner',
    days: 3,
    desc: 'Three sessions a week training the whole body each time. Alternate between workout A and B. A perfect place to start.',
    workouts: [
      W('Workout A', [['squat', 3, 8], ['bench-press', 3, 8], ['barbell-row', 3, 8], ['plank', 3, 30]]),
      W('Workout B', [['deadlift', 3, 5], ['overhead-press', 3, 8], ['lat-pulldown', 3, 10], ['crunches', 3, 15]]),
    ],
  },
  {
    id: 'p-5x5',
    name: 'Strength 5×5',
    level: 'Intermediate',
    days: 3,
    desc: 'Classic strength program built on heavy compound lifts. Add a little weight every session as long as you complete all reps.',
    workouts: [
      W('Workout A', [['squat', 5, 5], ['bench-press', 5, 5], ['barbell-row', 5, 5]]),
      W('Workout B', [['squat', 5, 5], ['overhead-press', 5, 5], ['deadlift', 1, 5]]),
    ],
  },
  {
    id: 'p-ppl',
    name: 'Push / Pull / Legs',
    level: 'Intermediate',
    days: 6,
    desc: 'Popular split where you train pushing, pulling and legs separately. Run it 3 or 6 days a week.',
    workouts: [
      W('Push', [['bench-press', 4, 8], ['db-incline-press', 3, 10], ['db-shoulder-press', 3, 10], ['lateral-raise', 3, 15], ['triceps-pushdown', 3, 12], ['overhead-triceps-extension', 3, 12]]),
      W('Pull', [['deadlift', 3, 5], ['pull-ups', 3, 8], ['seated-cable-row', 3, 10], ['face-pull', 3, 15], ['barbell-curl', 3, 10], ['hammer-curl', 3, 12]]),
      W('Legs', [['squat', 4, 8], ['romanian-deadlift', 3, 10], ['leg-press', 3, 12], ['leg-curl', 3, 12], ['standing-calf-raise', 4, 15]]),
    ],
  },
  {
    id: 'p-upper-lower',
    name: 'Upper / Lower',
    level: 'Intermediate',
    days: 4,
    desc: 'Four sessions a week split into upper body and lower body. A good balance between volume and recovery.',
    workouts: [
      W('Upper 1', [['bench-press', 4, 6], ['barbell-row', 4, 8], ['db-shoulder-press', 3, 10], ['lat-pulldown', 3, 10], ['db-curl', 3, 12], ['triceps-pushdown', 3, 12]]),
      W('Lower 1', [['squat', 4, 6], ['romanian-deadlift', 3, 8], ['lunges', 3, 10], ['leg-curl', 3, 12], ['standing-calf-raise', 3, 15], ['plank', 3, 45]]),
      W('Upper 2', [['incline-bench-press', 4, 8], ['pull-ups', 4, 8], ['arnold-press', 3, 10], ['db-row', 3, 10], ['hammer-curl', 3, 12], ['skull-crusher', 3, 10]]),
      W('Lower 2', [['deadlift', 3, 5], ['front-squat', 3, 8], ['hip-thrust', 3, 10], ['leg-extension', 3, 12], ['seated-calf-raise', 3, 15], ['hanging-leg-raise', 3, 12]]),
    ],
  },
  {
    id: 'p-bro-split',
    name: 'Classic Split (5 days)',
    level: 'Advanced',
    days: 5,
    desc: 'One muscle group per day for maximum volume. Suited to experienced lifters aiming for muscle growth.',
    workouts: [
      W('Chest', [['bench-press', 4, 8], ['db-incline-press', 4, 10], ['db-flyes', 3, 12], ['cable-crossover', 3, 15], ['dips', 3, 10]]),
      W('Back', [['deadlift', 4, 5], ['pull-ups', 4, 8], ['barbell-row', 4, 8], ['lat-pulldown', 3, 12], ['pullover', 3, 12]]),
      W('Shoulders', [['overhead-press', 4, 8], ['lateral-raise', 4, 15], ['reverse-flyes', 3, 15], ['face-pull', 3, 15], ['shrugs', 4, 12]]),
      W('Legs', [['squat', 5, 6], ['leg-press', 4, 10], ['romanian-deadlift', 3, 10], ['leg-extension', 3, 15], ['leg-curl', 3, 15], ['standing-calf-raise', 4, 15]]),
      W('Arms', [['barbell-curl', 4, 10], ['close-grip-bench', 4, 8], ['hammer-curl', 3, 12], ['triceps-pushdown', 3, 12], ['preacher-curl', 3, 12], ['overhead-triceps-extension', 3, 12]]),
    ],
  },
  {
    id: 'p-home',
    name: 'Home Workout, No Equipment',
    level: 'Beginner',
    days: 3,
    desc: 'Train your whole body at home using only your bodyweight. Works well as a circuit.',
    workouts: [
      W('Full body', [['bodyweight-squat', 3, 20], ['push-ups', 3, 12], ['lunges', 3, 12], ['glute-bridge', 3, 15], ['plank', 3, 40], ['burpees', 3, 10]]),
      W('Core and cardio', [['mountain-climbers', 3, 30], ['jumping-jacks', 3, 40], ['dead-bug', 3, 12], ['side-plank', 3, 30], ['russian-twist', 3, 20]]),
    ],
  },
  {
    id: 'p-band',
    name: 'Resistance Band Training',
    level: 'Beginner',
    days: 3,
    desc: 'Full-body program with resistance bands. Perfect at home or when travelling.',
    workouts: [
      W('Upper body', [['band-chest-press', 3, 15], ['band-row', 3, 15], ['band-shoulder-press', 3, 12], ['band-curl', 3, 15], ['band-triceps-extension', 3, 15], ['band-pull-apart', 3, 20]]),
      W('Lower body', [['band-squat', 3, 15], ['band-glute-bridge', 3, 20], ['band-lateral-walk', 3, 15], ['bodyweight-calf-raise', 3, 20], ['pallof-press', 3, 12]]),
    ],
  },
  {
    id: 'p-core',
    name: 'Strong Core',
    level: 'All levels',
    days: 2,
    desc: 'Short and effective core session that can be added after your regular training.',
    workouts: [
      W('Core workout', [['plank', 3, 60], ['side-plank', 3, 30], ['hanging-leg-raise', 3, 12], ['ab-wheel', 3, 10], ['pallof-press', 3, 12], ['dead-bug', 3, 12]]),
    ],
  },
  {
    id: 'p-glutes',
    name: 'Glutes and Legs',
    level: 'Intermediate',
    days: 2,
    desc: 'Focus on glutes and hamstrings.',
    workouts: [
      W('Glutes and legs', [['hip-thrust', 4, 10], ['bulgarian-split-squat', 3, 10], ['romanian-deadlift', 3, 10], ['cable-kickback', 3, 15], ['hip-abduction', 3, 15], ['band-lateral-walk', 2, 20]]),
    ],
  },
  {
    id: 'p-kettlebell',
    name: 'Kettlebell Circuit',
    level: 'Intermediate',
    days: 3,
    desc: 'Intense full-body session with a single kettlebell. Do all exercises back to back, rest and repeat.',
    workouts: [
      W('Circuit', [['kettlebell-swing', 4, 15], ['goblet-squat', 4, 12], ['turkish-get-up', 3, 3], ['farmers-walk', 3, 1]]),
    ],
  },
];

// Give workouts stable ids
PROGRAMS.forEach((p) => {
  p.builtin = true;
  p.workouts.forEach((w, i) => { w.id = `${p.id}-w${i}`; });
});
